export const USER_SIGNING_FAIL = "USER_SIGNING_FAIL";
export const USER_SIGNING_SUCCESS = "USER_SIGNING_SUCCESS";
export const USER_SIGNING_REQUEST = "USER_SIGNING_REQUEST";
export const USER_SIGNING_RESET = " USER_SIGNING_RESET";
//logout
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_RESET = " USER_LOGOUT_RESET";
